# Generated by Django 5.2.2 on 2025-06-18 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price of one unit of the product at the time of purchase.', max_digits=10, verbose_name='unit price')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount for this order (quantity * unit_price). Will be auto-calculated if not provided.', max_digits=12, verbose_name='total amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('transaction_id', models.CharField(blank=True, db_index=True, help_text='External transaction ID from payment provider or internal unique ID for the transaction event.', max_length=255, null=True, unique=True, verbose_name='transaction ID')),
                ('payment_method_details', models.JSONField(blank=True, help_text="Details about the payment method used, e.g., 'paid_with_internal_balance', simulated Stripe charge ID.", null=True, verbose_name='payment method details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('product', models.ForeignKey(help_text='The product purchased.', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='store.product')),
                ('user', models.ForeignKey(blank=True, help_text='User who made the purchase. Null if user is deleted or guest checkout.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
