# Generated by Django 5.2.2 on 2025-06-08 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the live session (e.g., Week 5 Lecture).', max_length=200, verbose_name='title')),
                ('room_id', models.CharField(default=uuid.uuid4, editable=False, help_text='Unique ID for the WebRTC room/session.', max_length=255, unique=True, verbose_name='room ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('live', 'Live'), ('ended', 'Ended')], default='pending', help_text='Current status of the live session.', max_length=10, verbose_name='status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='The course this live session belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='courses.course')),
                ('created_by', models.ForeignKey(help_text='The teacher who initiated this live session.', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_live_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Session',
                'verbose_name_plural': 'Live Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
