# Generated by Django 5.2.2 on 2025-06-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('item_type', models.CharField(choices=[('digital_good', 'Digital Good'), ('service_booking', 'Service Booking'), ('event_ticket', 'Event Ticket'), ('course_material_access', 'Course Material Access'), ('question_allowance', 'Question Allowance'), ('internal_credit_purchase', 'Internal Credit Purchase')], max_length=50, verbose_name='item type')),
                ('is_active', models.BooleanField(default=True, help_text='Is this product currently available for purchase?', verbose_name='is active')),
                ('stock_quantity', models.IntegerField(blank=True, help_text='For items with limited availability like tickets. Null means unlimited.', null=True, verbose_name='stock quantity')),
                ('meta_data', models.JSONField(blank=True, help_text='To store item_type specific data, e.g., course_id, event_id, credit_amount.', null=True, verbose_name='meta data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
