# Generated by Django 5.2.2 on 2025-06-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The common way a question is asked.', verbose_name='question text')),
                ('answer_text', models.TextField(help_text='The answer to be provided for the question.', verbose_name='answer text')),
                ('keywords', models.CharField(blank=True, help_text="Comma-separated keywords for matching queries. E.g., 'fees,payment,tuition'.", max_length=255, verbose_name='keywords')),
                ('category', models.CharField(blank=True, help_text="Optional category for organizing FAQs. E.g., 'Admissions', 'Technical Support'.", max_length=100, null=True, verbose_name='category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'FAQ Entry',
                'verbose_name_plural': 'FAQ Entries',
                'ordering': ['category', 'question_text'],
            },
        ),
    ]
