# Generated by Django 5.2.2 on 2025-06-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="User's internal balance.", max_digits=12, verbose_name='balance'),
        ),
    ]
